source: src
excerpt_separator: <!--more-->
include: ["_pages"]
permalink: /post/:title/
url: http://mlowl.com
exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - src
  - .eslintrc
  - README.md
  - _dist